# Generated by Django 3.1 on 2020-08-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmscomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn_comment', models.TextField()),
                ('cmspost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.cmspost')),
            ],
        ),
    ]
