# Generated by Django 3.1 on 2020-08-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmscomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmscomment',
            options={'verbose_name': 'نظرات', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='cmspost',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست'},
        ),
        migrations.AddField(
            model_name='cmspost',
            name='image',
            field=models.ImageField(default='temporary', upload_to='post_images/', verbose_name='عكس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmscomment',
            name='cmspost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.cmspost', verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='cmscomment',
            name='matn_comment',
            field=models.TextField(verbose_name='متن نظرات'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='date_post',
            field=models.DateTimeField(verbose_name='زمان و تاريخ'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='matn_post',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='cmspost',
            name='name_post',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
