# Generated by Django 3.1 on 2020-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_image_add_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspost',
            name='price_post',
            field=models.IntegerField(default='4900000', verbose_name='قيمت'),
            preserve_default=False,
        ),
    ]
