# Generated by Django 3.1 on 2020-08-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200824_2005'),
        ('cms', '0004_cmspost_price_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspost',
            name='sales_post',
            field=models.IntegerField(default=2, verbose_name='فروش محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmspost',
            name='shortage_post',
            field=models.IntegerField(default='3', verbose_name='كمبود محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmspost',
            name='status',
            field=models.IntegerField(choices=[(1, 'به فروش نرسيده'), (2, 'روانه بازار شده '), (3, 'اتمام موجودي'), (4, 'فروش محصول')], default=2, verbose_name='وضعيت'),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_count', models.IntegerField(verbose_name='تعداد خريد')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان خريد')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile', verbose_name='خريدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.cmspost', verbose_name='محصول')),
            ],
            options={
                'verbose_name': ('خريد',),
                'verbose_name_plural': ('خريد',),
            },
        ),
    ]
