# Generated by Django 3.1 on 2020-08-23 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('gender', models.IntegerField(blank=True, choices=[('مرد', 'MALE'), ('زن', 'FEMALE')], null=True, verbose_name='جنسيت')),
                ('brith_date', models.DateField(blank=True, null=True, verbose_name='تاريخ تولد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profile_images/', verbose_name='تصوير')),
                ('balance', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب كاربري')),
            ],
            options={
                'verbose_name': ('حساب كاربري',),
                'verbose_name_plural': ('حساب كاربري',),
            },
        ),
    ]
