# Generated by Django 3.1 on 2020-08-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200824_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراكنش')),
                ('transaction_code', models.CharField(max_length=30, verbose_name='رسيد تراكنش')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='كاربر')),
            ],
            options={
                'verbose_name': ('پرداخت',),
                'verbose_name_plural': 'پرداخت',
            },
        ),
    ]
